In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('diabetes.csv')

In [5]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [6]:
X = X.values
X.shape

(768, 8)

In [7]:
y = y.values.reshape(768,1)

In [8]:
y.shape

(768, 1)

In [9]:
W = np.random.randn(X.shape[1],y.shape[1])

In [10]:
def sigmoid(x):
    epsilon = 1e-5
    m = np.max(x)
    x = x/(m+epsilon)
    return 1/(1+np.exp(-x))

def predict(W):
    y_hat = np.dot(X,W)
    y_hat = sigmoid(y_hat)
    return y_hat

def loss(W):
    y_hat = predict(W)
    loss_ = y*np.log(y_hat) + (1-y)*np.log(1-y_hat)
    return -np.mean(loss_)

def grad(W):
    h = 1e-4
    grad = np.zeros_like(W)
    for i in range(W.shape[0]):
        for j in range(W.shape[1]):
            tmp = W[i,j]
            fx = loss(W)
            W[i,j] = tmp +h
            fxh = loss(W)
            grad[i,j] = (fxh - fx)/h
            W[i,j] = tmp
    return grad



In [11]:
W_ = np.array((W,np.array([0])))
W_

C:\Users\USER\AppData\Local\Temp\ipykernel_644\2322185672.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  W_ = np.array((W,np.array([0])))


array([array([[-0.22120951],
              [-0.14980575],
              [-2.11746663],
              [ 1.27096203],
              [-0.77959015],
              [ 0.01673763],
              [ 1.05109304],
              [-0.55179463]]), array([0])], dtype=object)

In [12]:
w, b = W_

In [13]:
b

array([0])

In [14]:
def predict(W):
    w, b = W
    y_hat = np.dot(X,w) + b
    y_hat = sigmoid(y_hat)
    return y_hat

def loss(W):
    y_hat = predict(W)
    loss_ = y*np.log(y_hat) + (1-y)*np.log(1-y_hat)
    return -np.mean(loss_)

def grad(W):
    h = 1e-4
    grad = np.zeros_like(W)
    for i in range(W.shape[0]):
        for j in range(W.shape[1]):
            tmp = W[i,j]
            fx = loss(W)
            W[i,j] = tmp +h
            fxh = loss(W)
            grad[i,j] = (fxh - fx)/h
            W[i,j] = tmp
    return grad

In [15]:
def grad(W):
    h = 1e-4
    w, b = W
    w_grad = np.zeros_like(w)
    for i in range(w.shape[0]):
        for j in range(w.shape[1]):
            tmp = w[i,j]
            fx = loss(W)
            w[i,j] = tmp +h
            fxh = loss(W)
            w_grad[i,j] = (fxh - fx)/h
            w[i,j] = tmp
    fx = loss(W)
    W = np.array((w,b+h))
    fxh = loss(W)
    b_grad = (fxh-fx)/h
    W = np.array((w,b))
    grad = np.array((w_grad,b_grad))
    return grad

In [16]:
for i in range(10000):
    W = W - 0.0001*grad(W)

ValueError: too many values to unpack (expected 2)

In [17]:
np.sum(np.where(predict(W)>0.5,1,0) ==  y)/y.size

ValueError: too many values to unpack (expected 2)

In [18]:
W = np.array((np.random.randn(X.shape[1],y.shape[1]),
             np.random.randn(y.shape[1])))

C:\Users\USER\AppData\Local\Temp\ipykernel_644\2409648721.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  W = np.array((np.random.randn(X.shape[1],y.shape[1]),


In [19]:
loss(W)

0.7779864894509331

In [20]:
W = np.random.randn(X.shape[1],y.shape[1])

In [21]:
import matplotlib.pyplot as plt

In [22]:
loss_val = []
for i in range(10000):
    W = W -0.0001*grad(W)
    loss_val.append(loss(W))
#    print(str(i+1),'번째 loss === ', loss(W))
plt.plot(np.arange(10000),loss_val)

ValueError: too many values to unpack (expected 2)

In [23]:
y_hat = np.where(predict(W) > 0.5,1,0)

ValueError: too many values to unpack (expected 2)

In [24]:
np.sum(y_hat.shape == y)/y.shape[0]

NameError: name 'y_hat' is not defined

In [25]:
y.shape

(768, 1)

In [26]:
sigmoid(np.dot(X,W))

array([[0.58098855],
       [0.60332878],
       [0.40517025],
       [0.44721206],
       [0.36291649],
       [0.48781851],
       [0.48924154],
       [0.45829155],
       [0.06093656],
       [0.46091809],
       [0.52831945],
       [0.45068493],
       [0.48948668],
       [0.01010354],
       [0.28395854],
       [0.47413196],
       [0.35416563],
       [0.50144577],
       [0.51221228],
       [0.46283315],
       [0.30728576],
       [0.54536923],
       [0.44783342],
       [0.57532972],
       [0.38907477],
       [0.39987831],
       [0.49334865],
       [0.35087122],
       [0.36952841],
       [0.52124321],
       [0.61645728],
       [0.24375021],
       [0.45782096],
       [0.50619972],
       [0.57419452],
       [0.32760777],
       [0.47244582],
       [0.6216039 ],
       [0.64586134],
       [0.38775031],
       [0.40305413],
       [0.50663242],
       [0.56470344],
       [0.25968706],
       [0.44856049],
       [0.55706486],
       [0.46369507],
       [0.604

In [27]:
def grad(W):
    grad = np.zeros_like(W)
    h = 1e-4
    for i in range(W.shape[0]):
        for j in range(W.shape[1]):
            tmp = W[i,j]
            fx = loss(W)
            W[i,j] = tmp + h
            fxh = loss(W)
            grad[i,j] = (fxh-fx)/h
            W[i,j] = tmp
    return grad

In [28]:
predict(W)

ValueError: too many values to unpack (expected 2)

In [29]:
for i in range(100):
    W = W - 0.001*grad(W)
    print(str(i+1),'번째 loss === ',loss(W))

ValueError: too many values to unpack (expected 2)

In [30]:
W

array([[-1.45833114],
       [-0.65984798],
       [ 0.31280631],
       [ 1.66352295],
       [-0.86898795],
       [ 1.21517167],
       [ 0.12933834],
       [ 0.72827702]])

In [31]:
# 활성화 함수 - 계딴함수 안씀

In [38]:
X = np.random.randn(100,7)
y = np.random.randn(100,5)

In [34]:
W_1 = np.random.randn(7,10)

In [35]:
b_1 = np.random.randn(10)

In [36]:
W_2 =np.random.randn(10,70)

In [37]:
b_2= np.random.randn(70)

In [39]:
w_3 = np.random.randn(70,5)

In [40]:
b_3= np.random.randn(5)

In [41]:
layer1 = np.dot(X,W_1) + b_1
layer2 = np.dot(layer1,W_2) + b_2
layer3 = np.dot(layer2,w_3) + b_3

In [42]:
layer3.shape

(100, 5)

In [43]:
layer1 = sigmoid(np.dot(X,W_1) + b_1)
layer2 = sigmoid(np.dot(layer1,W_2) + b_2)
layer3 = sigmoid(np.dot(layer2,w_3) + b_3)

In [ ]:
def sigmoid(x):
    epsilon = 1e-5
    m = np.max(x)
    x = x/(m+epsilon)
    return 1/(1+np.exp(-x))

In [ ]:
def relu(x):
    return np.where(x > 0,x,0)

In [ ]:
def tanh(x):
    return (np.exp(x)-np.exp(-x))/(np.exp(-x)+np.exp(x))

In [ ]:
df = pd.read_csv('diabetes.csv')

In [ ]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [ ]:
X.shape 
y.shape
## X,y 넘파이로 만들기
X = X.values
y = y.values

In [ ]:
y = y.reshape(-1,1)

In [ ]:
X.shape, y.shape

In [ ]:
1
Input_layer = np.random.randn(8,10)
2
#relu(Input_layer)
3
Hidden_layer = np.random.randn(10,150)
4
#relu(Hidden_layer)
5
Output_layer = np.random.randn(150,1)
6
#sigmoid(Output_layer)

In [ ]:
layer1 = np.dot(X,Input_layer)
activate1 = relu(layer1)
layer2 = np.dot(activate1,Hidden_layer)
activate2 = relu(layer2)
layer3 = np.dot(activate2,Output_layer)
output = sigmoid(layer3) # y_hat
#def predict()

In [ ]:
def loss(W):
    y_hat = predict(W)
    loss_ = y*np.log(y_hat) + (1-y)*np.log(1-y_hat)
    return -np.mean(loss_)

def loss_func(output):
    loss_ = y*np.log(output) + (1-y)*np.log(1-output)
    return -np.mean(loss_)

In [ ]:
loss_func(output)

In [ ]:
tmp = layer1[0,0] 

In [ ]:
layer1[0,0] = tmp

In [ ]:
layer1[0,0] = tmp+0.0001

In [ ]:
layer1 = np.dot(X,Input_layer)
activate1 = relu(layer1)
layer2 = np.dot(activate1,Hidden_layer)
activate2 = relu(layer2)
layer3 = np.dot(activate2,Output_layer)
output = sigmoid(layer3) # y_hat

In [ ]:
fxh = loss_func(output)

In [ ]:
fx = loss_func(output)

In [ ]:
(fxh - fx)/0.0001