In [6]:
# 1. 가설함수   ed ) ax+b
# 2. 예측결과  
# 3. 비용함수(손실함수) ex) mse, categorical cross~
# 4. 비용함수 최소화 => 미분 후 가설함수에 조금씩 반영하기

In [2]:
import numpy as np

In [45]:
X = np.random.randn(100)
y = X*3 + 4

In [46]:
X

array([-0.83636863, -0.70257018,  0.40441432, -0.52482692,  0.41266631,
       -0.9663402 , -0.24104499,  0.42556163,  0.64929177,  0.79581677,
       -0.0141099 ,  0.0777341 ,  1.78287284, -0.83100053, -1.16353098,
       -1.09022348, -0.01732714, -0.2924515 ,  1.34227324, -1.21587575,
        0.30084783, -0.57752105,  0.87101766,  0.13832386,  0.05282603,
        1.22048234,  0.46898582, -1.85395704,  0.19981929, -1.28005152,
        1.0355029 , -0.27622637, -0.02834171, -1.28501511, -0.67107553,
        0.03274525,  0.56622493,  0.20799659, -0.76320949, -0.97726959,
        0.254299  ,  1.22745332,  0.84169153,  0.24417212, -0.81968149,
        2.32187117,  0.61877506, -0.39361294,  0.58656237, -0.53329123,
       -0.04299392,  0.0370875 , -1.28117258,  2.20657106, -1.50706609,
       -1.73693991, -1.19096619, -0.12826355,  1.39555818,  0.06028445,
       -1.05856308,  0.9963931 ,  0.63291659,  2.04991394, -0.72817783,
        0.71754648, -0.67999561,  1.18826983, -0.67770305, -0.43

In [47]:
y

array([ 1.49089411,  1.89228946,  5.21324296,  2.42551923,  5.23799894,
        1.1009794 ,  3.27686502,  5.27668488,  5.94787531,  6.38745032,
        3.95767029,  4.23320229,  9.34861851,  1.50699842,  0.50940706,
        0.72932956,  3.94801859,  3.1226455 ,  8.02681971,  0.35237275,
        4.90254349,  2.26743686,  6.61305298,  4.41497158,  4.1584781 ,
        7.66144701,  5.40695747, -1.56187112,  4.59945787,  0.15984544,
        7.10650871,  3.17132088,  3.91497486,  0.14495467,  1.98677341,
        4.09823574,  5.69867479,  4.62398977,  1.71037154,  1.06819124,
        4.762897  ,  7.68235996,  6.52507459,  4.73251637,  1.54095553,
       10.96561352,  5.85632518,  2.81916119,  5.7596871 ,  2.40012631,
        3.87101825,  4.11126249,  0.15648227, 10.61971318, -0.52119828,
       -1.21081973,  0.42710143,  3.61520934,  8.18667454,  4.18085336,
        0.82431076,  6.9891793 ,  5.89874977, 10.14974182,  1.81546652,
        6.15263943,  1.96001318,  7.56480949,  1.96689086,  2.68

In [48]:
np.c_[X,y]

array([[-0.83636863,  1.49089411],
       [-0.70257018,  1.89228946],
       [ 0.40441432,  5.21324296],
       [-0.52482692,  2.42551923],
       [ 0.41266631,  5.23799894],
       [-0.9663402 ,  1.1009794 ],
       [-0.24104499,  3.27686502],
       [ 0.42556163,  5.27668488],
       [ 0.64929177,  5.94787531],
       [ 0.79581677,  6.38745032],
       [-0.0141099 ,  3.95767029],
       [ 0.0777341 ,  4.23320229],
       [ 1.78287284,  9.34861851],
       [-0.83100053,  1.50699842],
       [-1.16353098,  0.50940706],
       [-1.09022348,  0.72932956],
       [-0.01732714,  3.94801859],
       [-0.2924515 ,  3.1226455 ],
       [ 1.34227324,  8.02681971],
       [-1.21587575,  0.35237275],
       [ 0.30084783,  4.90254349],
       [-0.57752105,  2.26743686],
       [ 0.87101766,  6.61305298],
       [ 0.13832386,  4.41497158],
       [ 0.05282603,  4.1584781 ],
       [ 1.22048234,  7.66144701],
       [ 0.46898582,  5.40695747],
       [-1.85395704, -1.56187112],
       [ 0.19981929,

In [49]:
a = 1.
b = 2.
y_hat = a*X + b

In [50]:
loss = np.mean((y-y_hat)**2)

In [51]:
loss

7.624625000765496

In [11]:
# loss를 줄이는게 좋다

In [12]:
# (y-(a*X+b)**2)를 미분하자

# a로 미분 => 2x(ax+b-y) => 2x(y_hat - y)

# b로 미분 =>  

In [52]:
da = np.mean(2*X*(y_hat - y))
db = np.mean(2*(y_hat-y))

In [53]:
a = a - 1e-3*da
b=  b - 1e-3*db

In [54]:
a

1.0038048199047158

In [55]:
b

2.00381980509605

In [20]:
# 실제 값은 3,4인데 예측값 1,2에서 계속 하다보면 3,4로 맞춰 질 것이다

In [21]:
# 식으로 만들면?

In [56]:
for i in range(10000):
    y_hat = a*X + b
    loss = np.mean((y-y_hat)**2)
    da = np.mean(2*X*(y_hat-y))
    db = np.mean(2*(y_hat-y))
    a = a - 1e-3*da
    b = b - 1e-3*db

In [57]:
a

2.999999989489312

In [58]:
b

3.9999999898482206

In [64]:
# x1,x2로 하면?/

In [59]:
X = np.random.randn(100,2)
x1 = X[:,0]
x2 = X[:,1]
y = x1*8 + x2*3 + 10

In [60]:
np.c_[X,y]

array([[ 1.14820503e+00,  7.17134735e-01,  2.13370444e+01],
       [ 7.92689219e-01, -5.26203703e-01,  1.47629026e+01],
       [ 9.49284020e-03, -9.70732751e-01,  7.16374447e+00],
       [-6.29916473e-01,  2.02714268e-01,  5.56881102e+00],
       [-2.43972623e-01, -1.02217093e-01,  7.74156773e+00],
       [ 1.29768204e+00, -1.10010654e+00,  1.70811367e+01],
       [-1.55067013e-01,  1.04502479e+00,  1.18945383e+01],
       [-4.60829196e-01, -4.04360476e-01,  5.10028501e+00],
       [ 1.73196687e+00,  1.33001597e+00,  2.78457829e+01],
       [ 7.53455244e-01, -7.11495277e-01,  1.38931561e+01],
       [ 1.39357274e+00, -8.26646115e-01,  1.86686436e+01],
       [ 6.45288487e-01,  7.24629119e-01,  1.73361953e+01],
       [-2.64336483e-01,  1.53533626e+00,  1.24913169e+01],
       [-4.76421670e-01,  6.41467212e-01,  8.11302828e+00],
       [-8.23400116e-01, -6.73021095e-01,  1.39373579e+00],
       [ 5.41239275e-01, -1.73802275e-01,  1.38085074e+01],
       [ 5.82768725e-01, -9.29349816e-01

In [61]:
a1 = 100
a2 = -3
b = 0

In [62]:
for i in range(10000):
    y_hat = a1*x1 + a2*x2 + b
    loss = np.mean((y-y_hat)**2)
    da1 = np.mean(2*x1*(y_hat-y))
    da2 = np.mean(2*x2*(y_hat-y))
    db = np.mean(2*(y_hat-y))
    a1 = a1- 1e-3*da1
    a2 = a2- 1e-3*da2
    b =   b- 1e-3*db

In [63]:
a1, a2 ,b

(8.000056400454437, 2.9999789399182983, 9.99997158370143)

In [41]:
# 예측(100,-3,0) 개떡같이해도 만 번 loss 최소화 하다보면 실제 값(8,3,10)이 된다

In [65]:
# 한번에 묶엇 하는 방법 없을까 ? da1,da2....da1000있으면 번거롭다 => 행렬로 묶기

In [78]:
X = np.random.randn(100,3)
x1 = X[:,0]
x2 = X[:,1]
x3 = X[:,2]
y = 100*x1 + 7*x2 - 20*x3 + 80

In [79]:
W = np.array([[100],[7],[-20]])
y1 = np.dot(X,W) + 80


In [80]:
y= y.reshape(-1,1)

In [72]:
# 소수점이 약간 다르다

In [73]:
a1 = np.random.randn(1)
a2 = np.random.randn(1)
a3 = np.random.randn(1)
b = 0
y_hat = x1*a1 + x2*a2 + x3*a3 +b

In [81]:
W = np.random.randn(3,1)
b = 0

In [77]:
# 위에 했던놈이랑 차이점은 행렬에 대한 미분을 해야한다

In [87]:
for i in range(10000):
    y_hat = np.dot(X,W) + b
    loss = np.mean((y_hat-y)**2)
    dw = 2*np.dot(X.T,(y_hat-y))
    db = np.mean(2*(y_hat-y))
    W = W - 1e-4*dw
    b = b - 1e-4*db

In [88]:
W,b

(array([[ 99.99798034],
        [  7.0190994 ],
        [-20.00192272]]),
 79.73864489567023)

In [91]:
# dot이 있으니까 mean 할 필요가 없다 
# 1e-3 ,1e-4은 알아서 조정할것 
# 100,7,-20 ,80 다 나왔다

In [105]:
X = np.random.randn(100,20)
y = np.dot(X,np.random.randn(20,1)) + 100

In [106]:
W = np.random.randn(20,1)
b = 0

# X변수의 개수만큼 W 정해주면 나머지는 다 똑같다

In [107]:
for i in range(10000):
    y_hat = np.dot(X,W) + b
    loss = np.mean((y_hat-y)**2)
    dw = 2*np.dot(X.T,(y_hat-y))
    db = np.mean(2*(y_hat-y))
    W = W -1e-4*dw
    b = b - 1e-4*db

In [110]:
loss

# mse

339.88644304133993

In [111]:
# 

In [129]:
X = np.around(np.random.randn(100),2)
y = X*3

In [115]:
# 1.가설함수
# 2.loss function
# 3.loss 미분(미분식 = 위에서 한것 , 수치적방법 = 아래에서 할것)
# 4.미분값을 가설함수의 변수값 뺴주면 (최적화)
# 5. 학습 : (2~4) 반복

In [124]:
# np.c_[X,y] 얘 쓸 떄에는 [] 쓸 것

In [125]:
w = np.random.randn(1)
h = 1e-4
for i in range(10000):
    y_hat = w*X
    loss = np.mean((y_hat-y)**2) 
    fx = np.mean((y_hat-y)**2)
    y_hat_tmp = (w+h)*X
    fxh = np.mean((y_hat_tmp -y)**2)
    grad = (fxh - fx) / h
    w = w - 1e-3*grad

# (f(x+h)-f(x)) / h
# 느리다. 수치적미분은 

In [127]:
w

# 결과는 y= X*3 의 3으로 가까워지는게 맞다

array([2.99995])

In [128]:
# bias도 해보자

In [141]:
X = np.around(np.random.randn(100),2)
y = X*3 + 5

In [143]:
w = np.random.randn(1)
b = 0
h = 1e-4
for i in range(10000):
    y_hat = w*X + b
    loss = np.mean((y_hat-y)**2) 
    fx = np.mean((y_hat-y)**2)          
    #########################################
    y_hat_tmp = (w+h)*X + b
    fxh = np.mean((y_hat_tmp -y)**2)
    dw = (fxh - fx) / h
    fx = np.mean((y_hat-y)**2)
    y_hat_tmp = w*X+(b+h)
    fxh = np.mean((y_hat_tmp-y)**2)
    db = (fxh-fx)/h
    w = w - 1e-3*dw
    b = b - 1e-3*db


In [144]:
w,b

(array([2.99994529]), 4.999945640236048)

In [146]:
# 1.예측함수
# 2.비용함수
# 3.미분함수(수치미분)
# 4. 경사하강함수

In [160]:
# 0 데이터

x = np.random.randn(100)
y = x*7
w = np.random.randn(1)
# 1
def predict(w):
    return X*w
# 2
def loss(w):
    return np.mean((predict(w)-y)**2)
# 3
def grad(w):
    h = 1e-4
    fx = loss(w)
    fxh = loss(w+h) 
    grad = (fxh-fx)/h
    return grad
# 4
for i in range(10000):
    w = w - 1e-3*grad(w)

In [164]:
w

array([0.17224383])

In [163]:
# 위처럼 w뿐 아니라 b도 해보기

In [208]:
# 0 데이터

X = np.random.randn(100)
y = X*100 - 70
w = np.array((np.random.randn(1),0))

# 소문자, 대문자 잘쓰기

C:\Users\USER\AppData\Local\Temp\ipykernel_3944\2295183838.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  w = np.array((np.random.randn(1),0))


In [209]:
def predict(w):
    y_hat = X*w[0] + w[1] 
    return y_hat
def loss(w):
    y_hat = predict(w)
    return np.mean(2*(y_hat-y)**2)
def grad(w):
    h = 1e-4
    fx = loss(w)
    tmp = w[0]
    w[0] = tmp+h
    fxh = loss(w)
    dw = (fxh-fx)/h
    w[0] = tmp
    tmp = w[1]
    fx = loss(w)
    w[1] = tmp+h
    fxh = loss(w)
    db = (fxh-fx)/h
    result = np.array((dw,db))
    return result

In [210]:
# 4
for i in range(10000):
    w[0] = w[0] - 1e-3*grad(w)[0]
    w[1] = w[1] - 1e-3*grad(w)[1]

In [211]:
w

array([array([100.00015593]), -69.97514867751376], dtype=object)

In [212]:
b

4.999945640236048

In [213]:
# 변수가 여러개일 때~

In [259]:
X = np.random.randn(100,2)
W = np.array([[8],[-7]])
y = np.dot(X,W) + 1000

In [236]:
X.shape , y.shape

((100, 2), (100, 1))

In [260]:
w = np.random.randn(2,1)
b = 0
W = np.array((w,b))

C:\Users\USER\AppData\Local\Temp\ipykernel_3944\1050238314.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  W = np.array((w,b))


In [238]:
W

array([array([[0.63836522],
              [1.71704431]]), 0], dtype=object)

In [239]:
W[0][0] ,W[0][1] ,W[1]

(array([0.63836522]), array([1.71704431]), 0)

In [240]:
def predict(W):
    y_hat = np.dot(X,W[0]) + W[1]
    return y_hat
def loss(W):
    y_hat = predict(W)
    return np.mean(2*(y_hat-y)**2)
def grad(W):
    h = 1e-4
    tmp = W[0][0]
    fx = loss(W)
    W[0][0] = tmp + h
    fxh = loss(W)
    grad_1 = (fxh - fx) / h
    W[0][0] = tmp
    fx = loss(W)
    tmp = W[0][1]
    W[0][1] = tmp + h
    fxh = loss(W)
    grad_2 = (fxh -fx) / h
    W[0][1] = tmp
    tmp = W[1]
    fx = loss(W)
    W[1] = tmp + h
    fxh = loss(W)
    grad_b = (fxh-fx) /h
    w_ = np.c_[grad_1,grad_2].T
    grad = np.array((w_,grad_b))
    return grad
    

In [241]:
grad(W)

C:\Users\USER\AppData\Local\Temp\ipykernel_3944\1451833634.py:27: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  grad = np.array((w_,grad_b))


array([array([[ 385.17687237],
              [-141.88387897]]), -3995.3597937710583], dtype=object)

In [242]:
for i in range(10000):
    W[0] = W[0] - 1e-3*grad(W)[0]
    W[1] = W[1] - 1e-3*grad(W)[1]

C:\Users\USER\AppData\Local\Temp\ipykernel_3944\1451833634.py:27: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  grad = np.array((w_,grad_b))


In [243]:
W

array([array([[ 8.04775641],
              [-6.93765926]]), 1000.0272010020144], dtype=object)

In [244]:
#  저 위의 grad를 for문으로 바꿔보자

In [297]:
X = np.random.randn(100,2)
W = np.array([[8],[-7]])
y = np.dot(X,W) + 1000

In [298]:
w = np.random.randn(2,1)
b = 0
W = np.array((w,b))

C:\Users\USER\AppData\Local\Temp\ipykernel_3944\1050238314.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  W = np.array((w,b))


In [299]:
def grad(W):
    h = 1e-4
    grad_w = np.zeros_like(W[0])
    for i in range(W[0].shape[0]):
        for j in range(W[0].shape[1]):
            tmp = W[0][i,j]
            fx = loss(W)
            W[0][i,j] = tmp+h
            fxh = loss(W)
            grad_w[i,j] = (fxh-fx)/h
            W[0][i,j] = tmp
    tmp = W[1]
    fx = loss(W)
    W[1] = tmp+h
    fxh = loss(W)
    grad_b = (fxh-fx)/h
    W[1] = tmp
    grad = np.array((grad_w,grad_b))
    return grad

In [300]:
for i in range(10000):
    W[0] = W[0] - 1e-3*grad(W)[0]
    W[1] = W[1] - 1e-3*grad(W)[1]

C:\Users\USER\AppData\Local\Temp\ipykernel_3944\2015249953.py:18: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  grad = np.array((grad_w,grad_b))


In [305]:
W

# 병신같이 W구해놓고 w가 왜 안나오지 하지말기

array([array([[ 7.99995455],
              [-7.00006139]]), 999.9999447228346], dtype=object)

In [408]:
###################################################################이 밑으로는 안된다고 생각하고 다시 해보기##########################################################################

In [3]:
X = np.random.randn(100,3)
w1 = np.random.randn(3,10)
b1 = np.random.randn(1,10)
w2 = np.random.randn(10,1)
b2 = np.random.randn(1,1)
y = np.dot(X,w1) + b1
y = np.dot(y,w2) + b2

In [4]:
W = [
    [w1,b1],
    [w2,b2]
]

In [5]:
def predict(W):
    y_hat = X.copy()
    for i in range(len(W)):
        y_hat = np.dot(y_hat,W[i][0]) + W[i][1]
    return y_hat

def loss(W):
    y_hat = predict(W)
    return np.mean((y_hat-y)**2)

def grad(W):
    h = 1e-4
    grad_ = []
    for i in range(len(W)):
        grad_w = np.zeros_like(W[i][0])
        for row in range(W[i][0].shape[0]):
            for col in range(W[i][0].shape[1]):
                tmp = W[i][0][row,col]
                fx = loss(W)
                W[i][0][row,col] = tmp+h
                fxh = loss(W)
                grad_w[row,col] = (fxh-fx)/h
                W[i][0][row,col] = tmp
        grad_b = []
        for row in range(W[i][1].size):
            tmp = W[i][1][:,row]
            fx = loss(W)
            W[i][1][:,row] = tmp+h
            fxh = loss(W)
            grad_b.append((fxh-fx)/h)
            W[i][1][:,row] = tmp
        grad_b = np.array(grad_b).reshape(1,-1)
        grad_tmp = [grad_w,grad_b]
        grad_.append(grad_tmp)
    return grad_

In [7]:
def net(values):
    net = []
    row = X.shape[1]
    for value in values: 
        w = np.random.randn(row,value)
        b = np.random.randn(1,value)
        row = value
        tmp = [w,b]
        net.append(tmp)
    return net

In [8]:
X = np.random.randn(10000,200)
W = net([30,100,1])

In [9]:
y = predict(W)

In [11]:
# for i in range(10):
#     for j in range(len(W)):
#         W[j][0] = W[j][0] - 1e-3*grad(W)[j][0]
#         W[j][1] = W[j][1] - 1e-3*grad(W)[j][1]
        
# 돌리면 나오긴 하는데 2시간 걸린다

In [ ]:
오우;;\